google/automl

efficientdet/README.md

fix model_inspect command

---

efficientdet/README.md

`--data_dir` isn't a flag. The `--training_file_pattern` might be what was intended.

fix training command in README

---

efficientdet/anchors.py
efficientdet/inference.py
efficientdet/model_inspect.py

support Saved model

---

efficientdet/aug/autoaugment.py

fix dependencies

---

.gitignore

Testing copybara

---

efficientdet/utils.py

Revert the changes for summaries.

---

efficientdet/efficientdet_arch.py
efficientdet/hparams_config.py
efficientdet/utils.py

--
f65ca368012b054bf5489970148fd13311d9f0d9 by fsx950223 <fsx950223@gmail.com>:
add tpu args
--
e9edbc6e23aaff203f268b996b57833cdc8537aa by fsx950223 <fsx950223@gmail.com>:
add use_tpu to hparams
PiperOrigin-RevId: 305626435

Copybara import PR https://github.com/google/automl/pull/190

---

efficientdet/README.md

Fix #180 and #185.
PiperOrigin-RevId: 305631883

Minor fix to README.

---

efficientdet/efficientdet_arch.py

Fix https://github.com/google/automl/issues/144
PiperOrigin-RevId: 306081933

Add bifpn_dyn that can adapt to different min/max levels.

---

efficientdet/inference.py

I fix Example 2 in inference.py, in which serve_files function is replaced with serve_images.

fix Example 2 in inference.py

---

efficientdet/anchors.py
efficientdet/det_model_fn.py
efficientdet/efficientdet_arch.py
efficientdet/hparams_config.py
efficientdet/inference.py

Add channel first support.
Fix #54.

Data format

---

efficientdet/det_model_fn.py

I forget to add transpose when I submit pull request.
@mingxingtan

fix channels bug

---

efficientdet/efficientdet_arch_test.py
efficientdet/hparams_config_test.py
efficientdet/utils_test.py

Add a few simple tests.

---

efficientdet/inference.py
efficientdet/model_inspect.py

Fix https://github.com/google/automl/issues/142
PiperOrigin-RevId: 307913172

Explicitly write frozen graph.

---

efficientdet/det_model_fn.py
efficientdet/efficientdet_arch.py
efficientdet/efficientdet_arch_test.py
efficientdet/hparams_config.py

I'm not sure whether I should freeze ema?
Fix #273.

add freeze training

---

efficientdet/README.md
efficientdet/det_model_fn.py
efficientdet/efficientdet_arch.py
efficientdet/efficientdet_arch_test.py
efficientdet/g3doc/coco_ids.yaml
efficientdet/hparams_config.py
efficientdet/hparams_config_test.py
efficientdet/inference.py
efficientdet/main.py
efficientdet/model_inspect.py
efficientdet/utils.py
efficientdet/utils_test.py

Mainly follow up https://github.com/google/automl/pull/309

Clean up and some followup tests for config-based inference.

---

efficientdet/utils.py
efficientdet/utils_test.py

Add mixed precision utilities.

---

efficientdet/anchors.py
efficientdet/det_model_fn.py
efficientdet/inference.py
efficientdet/model_inspect.py

```tf.image.combined_non_max_suppression```
cc @mingxingtan @itsliupeng

add dynampic batch size inference

---

efficientdet/README.md

Some people confuse how to inference images. I did also confuse.
#249

Add how to inference custom data.

---

efficientdet/README.md

Minor spelling changes and clarification on tensorflow version requirements

minor spelling changes

---

efficientdet/det_model_fn.py
efficientdet/hparams_config.py
efficientdet/iou_utils.py
efficientdet/iou_utils_test.py

Partially based on https://github.com/tensorflow/addons/pull/914
Related issue: https://github.com/google/automl/issues/270

Add IoU loss for box regression.

---

efficientdet/aug/autoaugment.py
efficientdet/aug/autoaugment_test.py
efficientdet/dataloader.py
efficientdet/hparams_config.py

https://arxiv.org/pdf/1912.02781.pdf
https://github.com/google-research/augmix.

add augmix

---

efficientdet/keras/efficientdet_arch_keras_test.py

add name check sample

---

efficientdet/README.md
efficientdet/det_model_fn.py
efficientdet/hparams_config.py
efficientdet/main.py

Awesome distribute strategy.
Fix #400,#28,#274,#261.

add horovod

---

efficientdet/det_model_fn.py
efficientdet/hparams_config.py
efficientdet/main.py

Followup to https://github.com/google/automl/pull/413

Use flag to control use_horovod.

---

efficientdet/model_inspect.py

fix inference_time calculation bug

fix inference_time calculation bug

---

efficientdet/keras/efficientdet_arch_keras.py
efficientdet/keras/efficientdet_arch_keras_test.py
efficientdet/keras/utils_keras.py
efficientdet/keras/utils_keras_test.py
efficientdet/main.py
efficientdet/utils.py

A follow up to https://github.com/google/automl/pull/435

Cleanup the strategy and sync batch norm.

---

efficientdet/README.md
efficientdet/det_model_fn.py
efficientdet/efficientdet_arch.py
efficientdet/inference.py
efficientdet/keras/efficientdet_arch_keras.py
efficientdet/main.py
efficientdet/model_inspect.py
efficientdet/utils.py

1. Add support to export TensorRT model.
2. Optional eval name.
3. A few simple fixes.

Sync internal changes.

---

efficientdet/README.md
efficientdet/dataloader.py
efficientdet/efficientdet_arch.py
efficientdet/efficientdet_arch_test.py

Simple format update to dataloader

---

efficientdet/keras/efficientdet_arch_keras.py
efficientdet/keras/efficientdet_arch_keras_test.py

I have finished the variable check with the tf1.x model.

fix fpn cells

---

efficientdet/aug/autoaugment.py

* to fix https://github.com/google/automl/issues/378
* based on https://github.com/google/automl/issues/161#issuecomment-612966054

Force to use cpu for depthwise_conv2d

---

efficientdet/README.md
efficientdet/anchors.py
efficientdet/inference.py

I got bad result.
I don't know why?

float16 nms

---

efficientdet/keras/efficientdet_arch_keras_test.py

fix keras tests

---

efficientdet/anchors.py
efficientdet/aug/autoaugment.py
efficientdet/det_model_fn.py
efficientdet/det_model_fn_test.py
efficientdet/efficientdet_arch.py
efficientdet/efficientdet_arch_test.py
efficientdet/hparams_config.py
efficientdet/hparams_config_test.py
efficientdet/inference.py
efficientdet/keras/efficientdet_arch_keras.py
efficientdet/utils.py
efficientdet/utils_test.py

Important changes:
1. Changed config to allow hierarchical dict or configs.
Minor changes:
2. Deleted some unless configs.
3. Added tests for focal loss.
4. Fixed some format and coding style issues.

A followup to #502 and merge some internal changes.

---

efficientdet/det_model_fn.py
efficientdet/det_model_fn_test.py

Hi @mingxingtan , I've been travelling this week and didn't get the chance to follow up on the comments on PRs #502 and #522 earlier. 
Here is a test for label smoothing. Please lmk if there is anything else to change or add. Thanks

test label smoothing

---

efficientdet/utils.py

Temp fix cpu float16 inference bug

---

efficientdet/backbone/efficientnet_model.py
efficientdet/inference.py
efficientdet/keras/efficientdet_arch_keras.py
efficientdet/keras/efficientdet_arch_keras_test.py
efficientdet/utils.py

Ensure same layer names under eager and graph mode.

---

efficientdet/dataloader.py
efficientdet/det_model_fn.py
efficientdet/iou_utils.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/efficientdet_keras_test.py
efficientdet/keras/train.py
efficientdet/keras/train_lib.py
efficientdet/keras/train_lib_test.py
efficientdet/keras/utils_keras.py
efficientdet/model_inspect.py

Could you test tf syncbatchnorm, I will use it in keras model? @mingxingtan
I'm not familiar with TPU, could you add tf2 TPU logic?
TF version: 2.3+

add train script

---

efficientdet/backbone/efficientnet_model.py
efficientdet/iou_utils.py
efficientdet/iou_utils_test.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/efficientdet_keras_test.py
efficientdet/keras/infer.py
efficientdet/keras/train_lib_test.py

Delete debug info.

---

efficientdet/det_model_fn.py
efficientdet/hparams_config.py
efficientdet/keras/postprocess.py
efficientdet/keras/postprocess_test.py

Replace pyfunc postprocessing with the new keras utility.

---

efficientdet/dataloader.py
efficientdet/keras/train_lib.py
efficientdet/keras/train_lib_test.py

add logs to tensorboard

---

efficientdet/keras/eval.py
efficientdet/keras/infer.py

Currently it hardcodes the location of the COCO dataset and the model to use.

Add flags to the keras eval script.

---

efficientdet/coco_metric.py
efficientdet/det_model_fn.py
efficientdet/efficientdet_arch.py
efficientdet/efficientdet_arch_test.py
efficientdet/hparams_config.py
efficientdet/iou_utils.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/fpn_configs.py
efficientdet/keras/fpn_configs_test.py
efficientdet/keras/train_lib.py
efficientdet/keras/train_lib_test.py
efficientdet/model_inspect.py
efficientdet/utils.py

Also fix learning rate, add epoch summary, and add other code clean up

Add QuFPN per #580.

---

efficientdet/dataloader.py
efficientdet/dataloader_test.py
efficientdet/hparams_config.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/efficientdet_keras_test.py
efficientdet/keras/postprocess.py
efficientdet/keras/segmentation.py

Segmentation model

---

efficientdet/iou_utils.py
efficientdet/keras/eval.py
efficientdet/keras/infer.py

use model_dir as default ckpt path

---

efficientdet/model_inspect.py

Allow exporting saved model for network.

---

efficientdet/dataloader.py
efficientdet/det_model_fn.py
efficientdet/g3doc/faq.md
efficientdet/hparams_config.py
efficientdet/inference.py
efficientdet/keras/train_lib.py
efficientdet/keras/train_lib_test.py
efficientdet/keras/utils_keras_test.py
efficientdet/utils.py

A few cleanups on jitter and inspect tools.

---

efficientdet/keras/eval.py
efficientdet/keras/wbf.py
efficientdet/keras/wbf_test.py

Implements multi-scale tta + wbf's confidence scaling based on the number of boxes.
d0 + multiscale tta gets an AP of 37.1, an improvement of 1.3 over the highest single resolution used when paired with flip tta (35.8)

Multi scale tta

---

efficientdet/iou_utils.py
efficientdet/iou_utils_test.py

According to https://github.com/fsx950223/addons/pull/1

fix diou and ciou norm calculate

---

efficientdet/iou_utils_test.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/efficientdet_keras_test.py
efficientdet/keras/eval.py
efficientdet/keras/train_lib_test.py
efficientdet/keras/wbf.py
efficientdet/keras/wbf_test.py
efficientdet/tensorrt.py

Allow irregular shape inputs.

---

efficientdet/det_model_fn.py
efficientdet/hparams_config.py
efficientdet/keras/efficientdet_keras.py

Also fixed resizing bugs.
PiperOrigin-RevId: 325692361

Use keras model in default and add gradient value and loss clipping.

---

efficientdet/coco_metric.py
efficientdet/det_model_fn.py
efficientdet/keras/eval.py

Fix #275
PiperOrigin-RevId: 325721677

Add per-class AP metrics.

---

efficientdet/README.md

Added the ckpt_path for exporting the best model while model conversion

add ckpt_path to export best model

---

efficientdet/efficientdet_arch.py

Abseil logging Warning if no variables matched with  given var_freeze pattern.

:wrench: var_freeze pattern warning if none variables matched.

---

efficientdet/hparams_config.py
efficientdet/main.py

add option run_epoch_in_child_process

---

efficientdet/backbone/efficientnet_builder.py
efficientdet/backbone/efficientnet_lite_builder.py
efficientdet/backbone/efficientnet_model.py
efficientdet/efficientdet_arch.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/infer.py

Fix https://github.com/google/automl/issues/705

fix keras export saved model

---

efficientdet/backbone/efficientnet_builder_test.py
efficientdet/backbone/efficientnet_lite_builder.py
efficientdet/backbone/efficientnet_model.py
efficientdet/backbone/efficientnet_model_test.py
efficientdet/keras/efficientdet_keras_test.py
efficientdet/keras/util_keras.py

Related #676.
I got same gradients when I ran test cases. Maybe there is something wrong with efficientdet detection model.

add gradients test

---

efficientdet/hparams_config.py

:bug: Minor Postives_momentum init Fix

---

efficientdet/aug/mosaic.py
efficientdet/aug/mosaic_test.py
efficientdet/backbone/efficientnet_builder_test.py
efficientdet/backbone/efficientnet_model.py
efficientdet/det_model_fn.py
efficientdet/hparams_config.py
efficientdet/inference.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/efficientdet_keras_test.py
efficientdet/keras/eval.py
efficientdet/keras/infer.py
efficientdet/keras/label_util.py
efficientdet/keras/train.py
efficientdet/keras/train_lib.py
efficientdet/keras/util_keras.py
efficientdet/main.py

Internal changes

---

efficientdet/det_model_fn.py
efficientdet/utils.py

fix syncbatchnorm

---

efficientdet/det_model_fn.py

fix eval metrics

---

efficientdet/main.py

follow fix #747

---

efficientdet/main.py

Use the correct eval batch size for non-tpu estimator.

---

efficientdet/keras/train_lib.py

fix test step training flag

---

efficientdet/aug/gridmask.py
efficientdet/aug/gridmask_test.py
efficientdet/dataloader.py
efficientdet/hparams_config.py

Hi, @mingxingtan 
I Have Added GridMask Augmentation and tested it on some sample data
GridMask Augmentation is one of SOTA augmentation for Computer Vision
Refer - https://arxiv.org/abs/2001.04086
For Results Refer - https://paperswithcode.com/paper/gridmask-data-augmentation/review/
They got 1.8+ increase in MAP for FastRcnn
The Code I Develop is in Core tensorflow with tf.function wrapper so it will run in static graph mode with performance boost.
Please test the result with this PR with finetuned hyperparametres.
Thanks

:zap: Added GridMask Augmentation

---

efficientdet/aug/gridmask.py
efficientdet/aug/gridmask_test.py
efficientdet/dataloader.py
efficientdet/det_model_fn.py
efficientdet/efficientdet_arch_test.py
efficientdet/hparams_config.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/inference.py
efficientdet/keras/inference_test.py
efficientdet/keras/inspector.py
efficientdet/keras/inspector_test.py
efficientdet/main.py
efficientdet/third_party/grad_checkpoint/grad.py

Sync with internal changes.

---

efficientdet/hparams_config.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/inference.py
efficientdet/keras/inspector.py
efficientdet/keras/model_optimization.py
efficientdet/keras/train.py
efficientdet/keras/train_lib.py

add model optimization example
model prune

add model optimization

---

efficientdet/backbone/efficientnet_model.py
efficientdet/hparams_config.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/model_optimization.py
efficientdet/keras/train.py
efficientdet/keras/train_lib_test.py
efficientdet/utils.py

Support training efficientdet-d7x(batch_size 2) by keras/train.py and Support training efficientdet-d6(batch_size 2) by main.py on GTX1080Ti(11G).
Thanks to @kartik4949 .

refact gradient checkpoints

---

efficientdet/aug/autoaugment.py
efficientdet/backbone/efficientnet_model.py
efficientdet/dataloader.py
efficientdet/dataset/create_coco_tfrecord.py
efficientdet/dataset/create_pascal_tfrecord.py
efficientdet/det_model_fn.py
efficientdet/hparams_config.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/inference.py
efficientdet/keras/inference_test.py
efficientdet/keras/inspector_test.py
efficientdet/keras/train.py
efficientdet/keras/train_lib.py
efficientdet/keras/train_lib_test.py
efficientdet/keras/util_keras.py
efficientdet/utils.py

Sync changes: mostly with format changes

---

efficientdet/det_model_fn.py

Adjust lr warmup init to batch size (#839)

---

efficientdet/README.md
efficientdet/dataset/inspect_tfrecords.py

Solves #838 
I think this will be helpful for early signs of bad dataset, it can save unnecessary issues and debugging time which could have been a silly data format or labelling issue.
I can add this script to visualize folder too.
@mingxingtan @fsx950223 thoughts?
p.s: @fsx950223 suggested to use tfrecords viewer but I think this solves third party tool usages and will be very handy.

:zap: Added visualization script

---

efficientdet/dataloader.py
efficientdet/dataset/inspect_tfrecords.py
efficientdet/det_model_fn.py
efficientdet/hparams_config.py
efficientdet/keras/README.md
efficientdet/keras/eval.py
efficientdet/keras/inference.py
efficientdet/keras/inspector.py
efficientdet/keras/label_util.py
efficientdet/keras/train.py
efficientdet/keras/train_lib.py
efficientdet/keras/train_lib_test.py
efficientdet/keras/util_keras.py

Sync Internal changes

---

efficientdet/keras/efficientdet_keras.py

Fix https://github.com/google/automl/issues/951.
Thanks @Mypathissional point it out.

fix fastattn

---

efficientdet/backbone/efficientnet_model.py
efficientdet/coco_metric.py
efficientdet/dataloader.py
efficientdet/dataset/tfrecord_util.py
efficientdet/hparams_config.py
efficientdet/inference.py
efficientdet/keras/anchors.py
efficientdet/keras/efficientdet_keras.py
efficientdet/keras/eval_tflite.py
efficientdet/keras/inference.py
efficientdet/keras/inference_test.py
efficientdet/keras/inspector.py
efficientdet/keras/postprocess.py
efficientdet/keras/postprocess_test.py
efficientdet/keras/train.py
efficientdet/keras/train_lib.py
efficientdet/keras/train_lib_test.py
efficientdet/keras/util_keras.py
efficientdet/utils.py

These changes are largely done by ziyeqinghan@ (Yuqi Li) for TFLite.

Merge internal changes.

---

efficientdet/README.md

add export to onnx turtorial

---

efficientdet/keras/efficientdet_keras.py
efficientdet/keras/segmentation.py

fix h5 weights

---

efficientnetv2/infer.py
efficientnetv2/mlir.py

Add mode tf2mlir that exports MLIR

---

efficientdet/utils.py
efficientnetv2/datasets.py
efficientnetv2/hparams.py
efficientnetv2/main_tf2.py
efficientnetv2/utils.py

!python main_tf2.py --mode=traineval  --model_name=efficientnetv2-b0  --dataset_cfg=tfflowersft --model_dir={MODEL}_finetune --hparam_str="train.ft_init_ckpt={MODEL},runtime.strategy=tpu,train.batch_size=512"

add colab tpu training example without gcs
