efficientdet/main.py
`logging.WARNING` is what is needed. `logging.warning` is a function.
=> fix typo in verbosity level

efficientdet/README.md
`-o FILE` logs cli output to FILE.
`-O FILE` writes the download to FILE.
See man page for details.
=> Fix misbehaving wget command in readme

efficientdet/anchors.py
Enable native nms as default, because it's much faster than nms_tf and they get same result.
=> enable native nms as default

efficientdet/README.md, efficientdet/efficientdet_arch.py, efficientdet/hparams_config.py, efficientdet/inference.py, efficientdet/main.py, efficientdet/model_inspect.py
When developing custom models, I had to edit the `hparams_config.py` file because I was changing too many parameters to use the `--hparams` option. The hyper-parameters also need to stay the same between training and inference, and `inspect_model.py` did not take the `--hparams` option. This made pulling updates hard because of merge conflicts in the config file.
I made `model_inspect.py` accept the `--hparams` option, and modified `--hparams` to take either a python module or key-value pairs.
Example:
```
python model_inspect.py --model_name efficientdet-d0  \
--runmode=infer --ckpt_path=ckpt \
--hparams=config  \
--input_image=test.jpg  --output_image_dir=/tmp
```
Where `config.py` is a file containing the hyper-parameters for the scaled-down model I want to use to recognize persons and …
=> Accept custom hyper-parameter files 

efficientdet/det_model_fn.py
There was a bug introduced with commit 325f2b2f597c90f9867e3688b82854b3a741c92d.
Variable `l2loss` was not defined anymore.
=> bug due to name change

efficientdet/inference.py
Fixes a bug I encountered when trying to set min_score_thresh=0 during inference; it was replaced by the default value (0.4).
=> Allow min_score_thresh=0 during inference

efficientdet/anchors.py, efficientdet/det_model_fn.py, efficientdet/hparams_config.py, efficientdet/inference.py, efficientdet/utils.py, efficientdet/utils_test.py
Hi @mingxingtan
I'd like to implement some of the cheap tricks used in the  [yolo4  paper](https://arxiv.org/pdf/2004.10934.pdf) to increase EfficientDet's performance.
Here are some of the things I'm thinking of implementing and testing:
- CIOU loss
Maybe you've thought of this before. Do you have any insights/suggestions concerning this line of work? Have any of these been tried for this project?
Thanks!
=> Add Yolo4 tricks to improve performance [WIP]

efficientdet/aug/autoaugment.py
Summary:
Updated imports to fix accessing `Beta` and `Dirichlet` distributions when `tensorflow_probability` is not available for import.
Issue:
If `tensorflow_probability` is not available for import, `tensorflow.distributions` is mapped to `tfp` instead.  `tfp` is used for `tfp.distributions.Beta` and `tfp.distributions.Dirichlet` which provide the following error when called:
```
AttributeError: module 'tensorflow.distributions' has no attribute 'distributions'
```
=> fix importing distributions when tfp not available

efficientdet/coco_metric.py
In evaluation function when filename is not present we need to initialize Coco there as well.
cc @mingxingtan
=> initialize coco metric when filename is not present

efficientdet/keras/eval.py, efficientdet/keras/postprocess.py, efficientdet/keras/postprocess_test.py, efficientdet/keras/wbf.py, efficientdet/keras/wbf_test.py
Implements [Weighted Boxes Fusion](https://arxiv.org/pdf/1910.13302.pdf) for test time augmentation, currently only with 2 inferences per image (regular, and left-right flip).  I based my code on the [author's implementation of WBF](https://github.com/ZFTurbo/Weighted-Boxes-Fusion/blob/master/ensemble_boxes/ensemble_boxes_wbf.py).
I'm opening this as a draft because my current code has terrible performance.  I can eval the COCO validation set with d0 in 5-10 minutes normally, but with this code it take much longer (I don't know how long yet because the job hasn't actually finished, but probably 1 day+).  I am using a O(n^2) algorithm to cluster the boxes, but there are only 200 boxes per image, and we do something similar for the NMS with many more boxes, so I don't think that's it.  Any …
=> Add test time augmentation

efficientdet/keras/wbf.py, efficientdet/keras/wbf_test.py
Before, the clustered boxes were averaged together without taking into account the model's confidence.  Doesn't improve AP much (~0.0005 AP) currently, since the left-right flip mostly preserves confidence, but should help more with multi-scale tta.
=> Actually do *weighted* box fusion.

efficientdet/keras/infer.py
Somehow when a list of numpy arrays is passed to _preprocess, map_fn will use dim[0] of the first element in the list as n_static. A quick fix by converting the list to 4D tensor (for single image).
=> Fix preprocessing error in keras infer

efficientdet/keras/train_lib.py
When `val_loss` is used as metric for `EarlyStopping` monitoring, it only takes in scalar for comparison, raising the following error: `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`, since `loss_vals['loss']` is a 1st order tensor. A simple fix is to only add `det_loss[0]` to `total_loss`.
=> Fix an issue which prevents EarlyStopping callback

efficientdet/keras/train.py, efficientdet/keras/train_lib.py
Currently, the flag `model_dir` is used for both loading and saving the checkpoint file in the keras training script. This will lead to a problem of overwriting the original checkpoint.
For example, if `model_dir=ckpt/efficientdet-d0`, the script will look for the latest checkpoint file inside the directory, where the filename is `model.*` if the pretrain weight downloaded from the repo is used. During training, checkpoint files are saved at `ckpt/efficientdet-d0.*`, at the same level of the original `model_dir`. After training is finished, the final checkpoint files called `model.*` are saved inside `model_dir`, potentially overwriting the original checkpoint, which might be intended to be kept.
With this PR, another flag called `ckpt` is created to take the directory of pretrained …
=> Separating input and output model checkpoint, avoiding file overwriting.

efficientdet/efficientdet_arch.py
When pattern is not set an error is produced 
File "C:\Users.....\efficientdet\efficientdet_arch.py", line 51, in freeze_vars
return _variables
UnboundLocalError: local variable '_variables' referenced before assignment
=> Update efficientdet_arch.py freeze_vars error

efficientdet/aug/mosaic.py, efficientdet/aug/mosaic_test.py
This is mosaic augmentation module in tf2,currently this augmentation doesnt preserve aspect ratio of original images passed
also it only supports 4 images to build mosaic.
Note: Tested in TF2 with eager execution and static graph.
=> Added Mosaic Augmentation in core TF

efficientdet/inference.py
I was following the notebook tutorial and an error occurred when I was trying to export my model using model_inspect.py:
```
python model_inspect.py \
--runmode=saved_model \
--model_name=$MODEL \
--ckpt_path=$MODEL_DIR_TMP \
--saved_model_dir=$MODEL_DIR_EXPORT
```
The exception prints out:
```
Traceback (most recent call last):
File "model_inspect.py", line 520, in <module>
app.run(main)
File "/home/ml6/projects/CCPD/ccpd-efficientdet/source/venv/lib/python3.6/site-packages/absl/app.py", line 300, in run
_run_main(main, args)
File "/home/ml6/projects/CCPD/ccpd-efficientdet/source/venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
sys.exit(main(argv))
File "model_inspect.py", line 513, in main
trace_filename=FLAGS.trace_filename)
File "model_inspect.py", line 462, in …
```
=> small bug fix: model exporting type cast error

efficientdet/main.py
If folder has no checkpoint or folder does not exists, then another error occurres within exception. Training still works, only prevents potential confusion.
My versions:
- TF 2.3.0
- Python 3.6.9
```
--- Logging error ---
Traceback (most recent call last):
File "xxx/projects/automl-efficientdet/efficientdet/main.py", line 348, in main                                                                                                                                                step = int(os.path.basename(ckpt).split("-")[1])
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
msg = self.format(record)
File …
```
=> fixed TypeError: not all arguments converted during string formatting

efficientdet/det_model_fn.py, efficientdet/main.py
After asking TF team, looks like tf.estimator.train_and_eval is recommended for continuous train_and_eval, as it avoids rebuild graph for every train.
=> Simplify estimator train_and_eval.

efficientdet/keras/efficientdet_keras.py
Fix #676 
Only happens when moving average decay = 0 and use_keras_model = True.
Reason: utils.get_ema_variable only return trainable variables that cause WSM variables aren't restored when set is_training_bn = False.
=> remove trainable

efficientdet/dataset/create_pascal_tfrecord.py, efficientdet/dataset/tfrecord_util.py
Although the conversion script supports loading custom label map (via the `label_map_json_path` flag), it always tries to load the list of examples from `aeroplane_<set>.txt` file. This fails in most cases (unless the custom dataset actually does contain the `aeroplane` class).
This PR modifies the behavior and instead of using hard-coded class, it picks the class directly from `label_map_dict`.
It also creates the output directory, if it doesn't exist.
=> Improve handling of custom label maps

efficientdet/README.md, efficientdet/hparams_config.py
This is a better default for gradient_checkpointing_list.
Currently it is ['Add'] and, therefore, BiasAdd nodes are included in checkpoints - this was unintended as the intention was to include only "bottleneck" nodes.
With the new default, the number of checkpoints to include decreases (e.g. for d6 it goes from ~300 to ~100) so it uses slightly less memory. I am not able to measure exact decrease in memory usage as I noticed that tf reserves more memory (all available memory) than it actually needs. But I am able to train more models. E.g. d6 with batch 2 with XLA enabled was giving me OOM and now it trains fine. For some not fully understood reason (maybe saving/reading checkpoints from cache is a more expensive operation than I originally thought) the overall speed of the …
=> default gradient_checkpointing_list ['AddN', 'Add_']

efficientdet/main.py
Disable run_epoch_in_child_process in default, since it always creates strange bugs, such as:
```
Process Process-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
return fn(*args)
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1348, in _run_fn
self._extend_graph()
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1388, in _extend_graph
tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by {{node NcclAllReduce}} with these attrs: [num_devices=2, reduction="sum", shared_name="c0", T=DT_FLOAT]
Registered …
```
=> disable run_epoch_in_child_process in default

efficientdet/README.md, efficientdet/dataloader.py, efficientdet/det_model_fn.py, efficientdet/inference.py, efficientdet/keras/efficientdet_keras.py, efficientdet/keras/infer.py, efficientdet/keras/inference.py, efficientdet/keras/train.py, efficientdet/keras/train_lib.py, efficientdet/keras/util_keras.py, efficientdet/main.py, efficientdet/requirements.txt, efficientdet/utils.py
cc @mingxingtan 
I met some issues when I train the model with keras multi gpus on tf2.4, could you check it?
I wonder it's a bug of my environment or tensorflow.
=> update for tf2.4

efficientdet/dataset/inspect_tfrecords.py, efficientdet/keras/inspector.py
Benchmarking with `only_network` was not possible due to incorrect data type of the synthetic tensor.
The `inspect_tfrecords.py` utility ignored all bounding boxes with `ymin` equal to 0. These are now correctly rendered.
It also used red color for all bounding boxes which sometimes made it difficult to distinguish different object classes if they were clustered. It now behaves identically to inference of `keras.inspector` module and uses different color for each class.
Video exported using the `keras.inspector` module now dynamically sets the frame rate of output file equal to the input file.
=> Fix inspectors

efficientdet/README.md, efficientdet/keras/README.md, efficientdet/keras/efficientdet_keras.py, efficientdet/keras/inference.py, efficientdet/keras/inspector.py, efficientdet/keras/postprocess.py, efficientdet/keras/train.py, efficientdet/keras/util_keras.py
I fix the nms bug on float16 kernel, I have uploaded the code on https://github.com/fsx950223/tensorflow/commits/non_max_suppression.
Here is my minimal example:
```
import tensorflow as tf
boxes_f = open('/tensorflow_src/tensorflow/examples/tests/boxes.tensor', 'rb').read()
scores_f = open('/tensorflow_src/tensorflow/examples/tests/scores.tensor', 'rb').read()
boxes = tf.io.parse_tensor(boxes_f, tf.float16)
scores = tf.io.parse_tensor(scores_f, tf.float16)
nms_top_idx, nms_scores, nms_valid_lens = tf.raw_ops.NonMaxSuppressionV5(
boxes=boxes,
scores=scores,
max_output_size=100,
iou_threshold=1.0,
score_threshold=0.3,
soft_nms_sigma=(0.5 / 2),
pad_to_max_output_size=True)
tf.print(nms_top_idx, nms_scores, nms_valid_lens)
```
You can download tensors from …
=> fix nms numeric stable bug

efficientdet/inference.py
@mingxingtan 
havent profiled the actual gains but inference working fine with efficientdet-d0 exported model without batch_size i.e batch_size = None
may be we can get rid of the while with this now.
=> Vectorized batch inference

efficientnetv2/README.md, efficientnetv2/tutorial.ipynb
Fixes for EfficientNetv2 documentation.
- README snippet for fine tuning references `pretrained` param in `effnetv2_model.get_model`, but that param does not exist anymore.
- `tutorial.ipynb` references a non-existant variable `labels_file` instead of `labels_map`
=> Fix README for fine-tuning and tutorial typo

efficientdet/README.md
I think the `Prameters` count for `EfficientDet-lite` models are not correct:
```py
import hparams_config
import inference
from tf2 import efficientdet_keras
config = hparams_config.get_efficientdet_config('efficientdet-lite0')
model = efficientdet_keras.EfficientDetNet(config=config)
model.build((None, config.image_size, config.image_size, 3))
model.summary()
```
Summary results:
| Model               | Total params | Trainable params |
| ------------------- | ------------ | ---------------- |
| efficientdet-lite0  | 3,290,606    | 3,243,470        |
| efficientdet-lite1  | 4,311,390    | 4,248,318        |
| efficientdet-lite2  | 5,324,894    | 5,252,334        |
| efficientdet-lite3  | 8,455,054    | 8,350,862        |
| efficientdet-lite3x | 9,392,574    | 9,280,862        |
| …
=> Parameter count for EfficientDet lite models

efficientnetv2/effnetv2_model.py
When I use efficientnet-l2 model, it gets the pretrained ckpt of l2_475 and error occurs.
So, I fixed pretarained ckpt of l2 and l2_475.
=> fix pretrained ckpt of efficientnet-l2

lion/lion_pytorch.py
Fix the inplace sign operation in torch.  This should solve the issue #1201 brought in commit #1193.
=> Fix the inplace sign operation

efficientdet/requirements.txt
This patch modifies the requirements file to only install TensorFlow versions older than 2.16.0, since some breaking changes made it incompatible with the efficientdet repository (like the removal of the Estimator API). It also tightens the dependency on numpy, since version 1.24.0 removed some deprecated type aliases used by cocoapi, like `np.float`.
=> efficientdet: update requirements.txt
